export enum UIFeatureType {
  SCREEN = 'SCREEN',
  BUTTON = 'BUTTON',
  COMPONENT = 'COMPONENT',
  TAB = 'TAB',
  MENU_ITEM = 'MENU_ITEM',
  SECTION = 'SECTION',
}

export enum UIFeatureCategory {
  FREIGHT = 'FREIGHT',
  DASHBOARD = 'DASHBOARD',
  COMPANY = 'COMPANY',
  USERS = 'USERS',
  REPORTS = 'REPORTS',
  SETTINGS = 'SETTINGS',
  INTEGRATIONS = 'INTEGRATIONS',
  FINANCIAL = 'FINANCIAL',
  ANALYTICS = 'ANALYTICS',
  NOTIFICATIONS = 'NOTIFICATIONS',
}
