export enum VehicleType {
  THREE_QUARTER = 'Três Quartos',
  FIORINO = 'Fiorino',
  STUMP = 'Toco',
  VCL = 'VCL',
  BIT_TRUCK = 'Bitruck',
  TRUCK = 'Truck',
  BI_TRAIN = 'Bitrem',
  CART = 'Carreta',
  CART_LS = 'Carreta LS',
  ROAD_TRAIN = 'Rodotrem',
  VANDERLEIA = 'Vanderleia',
  ALLLIGHT = 'Leve',
  THREE_FOUR = 'Três Quartos',
  TOCO = 'Toco',
  ALLWEIGHT = 'Pesado',
  TRAINWHELL = 'Rodotrem',
  ALLAVERAGE = 'Médio',
}

export enum BodyType {
  CHEST = 'Baú',
  FRIDGE_CHEST = 'Baú Frigorífico',
  REFRIGERATED_CHEST = 'Baú Refrigerado',
  SIDER = 'Sider',
  BUCKET = 'Caçamba',
  LOW_GRILLE = 'Grade Baixa',
  BULK_CARRIER = 'Graneleiro',
  PLATFORM = 'Plataforma',
  BOARD = 'Prancha',
  ONLY_HORSE = 'Cavalo Mecânico',
  BUG_CONTAINER_DOOR = 'Container',
  PRATTLE = 'Gaiola',
  BLINKER = 'Basculante',
  CAVAQUEIRA = 'Cavaqueira',
  CAGE = 'Gaiola',
  CONTAINER = 'Container',
  HOPPER = 'Hopper',
  MUNK = 'Munck',
  SILO = 'Silo',
  TANK = 'Tanque',
}
